[features]
seeds = false
skip-lint = false

[programs.devnet]
solana = "kMmjwkAfsWhh2m6mqkEgn3i4BdrTZFMow8UeTvLq25K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/simon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
